"""
app.py
──────
EduPredict Flask API — served by Gunicorn in production.

Development:
    python app.py

Production (Gunicorn):
    gunicorn --config gunicorn.conf.py app:app
    # or directly:
    gunicorn -w 4 -b 0.0.0.0:5000 app:app
"""

from flask import Flask, request, jsonify
import joblib
import os
import numpy as np
import logging

# ── Logging ───────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s  %(levelname)-8s  %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S',
)
logger = logging.getLogger(__name__)

# ── Load model & scaler ───────────────────────────────────────────────────────
# Both files are generated by running: python train_model.py
BASE_DIR    = os.path.dirname(os.path.abspath(__file__))
MODEL_PATH  = os.getenv('MODEL_PATH',  os.path.join(BASE_DIR, 'logistic_model.joblib'))
SCALER_PATH = os.getenv('SCALER_PATH', os.path.join(BASE_DIR, 'scaler.joblib'))

logger.info(f"Loading model  → {MODEL_PATH}")
logger.info(f"Loading scaler → {SCALER_PATH}")

model  = joblib.load(MODEL_PATH)
scaler = joblib.load(SCALER_PATH)

logger.info("Model and scaler loaded successfully.")

# ── App factory ───────────────────────────────────────────────────────────────
app = Flask(__name__)


# ── Routes ────────────────────────────────────────────────────────────────────

@app.route('/predict', methods=['POST'])
def prediction():
    """
    Predict exam pass/fail probability based on student metrics.

    Expected JSON body:
    {
        "study_hours":          float,
        "self_study_hours":     float,
        "online_classes_hours": float,
        "mental_health_score":  float
    }

    Returns:
    {
        "exam_score_prob": float,   # probability of passing (0.0 – 1.0)
        "fail_prob":       float,   # probability of failing (0.0 – 1.0)
        "alerts":          [str]    # list of warning messages
    }
    """
    data = request.get_json(silent=True)
    if data is None:
        return jsonify({'error': 'Request body must be valid JSON'}), 400

    # ── Validate required fields ──────────────────────────────────────────────
    required_fields = [
        'study_hours', 'self_study_hours',
        'online_classes_hours', 'mental_health_score',
    ]
    missing = [f for f in required_fields if f not in data]
    if missing:
        return jsonify({'error': f'Missing fields: {missing}'}), 400

    try:
        study_hours          = float(data['study_hours'])
        self_study_hours     = float(data['self_study_hours'])
        online_classes_hours = float(data['online_classes_hours'])
        mental_health_score  = float(data['mental_health_score'])
    except (ValueError, TypeError) as e:
        return jsonify({'error': f'Invalid field value: {str(e)}'}), 400

    logger.info(
        f"Predicting for study={study_hours}h  self={self_study_hours}h  "
        f"online={online_classes_hours}h  mental={mental_health_score}"
    )

    # ── Scale & predict ───────────────────────────────────────────────────────
    features        = np.array([[study_hours, self_study_hours,
                                  online_classes_hours, mental_health_score]])
    features_scaled = scaler.transform(features)

    exam_score_prob = float(model.predict_proba(features_scaled)[0][1])
    fail_prob       = 1.0 - exam_score_prob

    # ── Alerts ────────────────────────────────────────────────────────────────
    alerts = []
    if study_hours == 0:
        alerts.append("You haven't studied today. Try to study to increase your exam scores.")
    if self_study_hours < 2:
        alerts.append("Self study hours are very low.")
    if online_classes_hours < 3:
        alerts.append("Online classes hours are short.")
    if mental_health_score < 5:
        alerts.append("Your mental health is not good. Relax or seek help to improve wellness.")
    if exam_score_prob < 0.7:
        alerts.append(
            f"Your exam score probability is only {exam_score_prob * 100:.1f}%."
            " Consider improving your study habits."
        )

    logger.info(f"Result → pass={exam_score_prob:.4f}  fail={fail_prob:.4f}  alerts={len(alerts)}")

    return jsonify({
        'exam_score_prob': round(exam_score_prob, 4),
        'fail_prob':       round(fail_prob, 4),
        'alerts':          alerts,
    })


@app.route('/health', methods=['GET'])
def health():
    """Health check — confirms server, model, and scaler are all loaded."""
    return jsonify({
        'status':        'ok',
        'model_loaded':  model is not None,
        'scaler_loaded': scaler is not None,
    })


# ── Dev server ────────────────────────────────────────────────────────────────
# In production, Gunicorn calls `app` directly — this block is only for local
# development via `python app.py`.

if __name__ == '__main__':
    port = int(os.getenv('PORT', 5000))
    print("=" * 52)
    print(f"  EduPredict API  —  http://0.0.0.0:{port}")
    print("  POST /predict   →  exam prediction")
    print("  GET  /health    →  server status")
    print("  [DEV MODE — use Gunicorn for production]")
    print("=" * 52)
    app.run(host='0.0.0.0', port=port, debug=True)
