from flask import Flask, request, jsonify
import joblib
import os
import numpy as np

# ── Load model & scaler ───────────────────────────────────────────────────────
# Both files are generated by running: python train_model.py
BASE_DIR    = os.path.dirname(os.path.abspath(__file__))
MODEL_PATH  = os.getenv('MODEL_PATH',  os.path.join(BASE_DIR, 'logistic_model.joblib'))
SCALER_PATH = os.getenv('SCALER_PATH', os.path.join(BASE_DIR, 'scaler.joblib'))

model  = joblib.load(MODEL_PATH)
scaler = joblib.load(SCALER_PATH)

app = Flask(__name__)


@app.route('/predict', methods=['POST'])
def prediction():
    """
    Predict exam pass/fail probability based on student metrics.

    Expected JSON body:
    {
        "study_hours": float,
        "self_study_hours": float,
        "online_classes_hours": float,
        "mental_health_score": float
    }

    Returns:
    {
        "exam_score_prob": float,   # probability of passing (0.0 – 1.0)
        "fail_prob": float,          # probability of failing (0.0 – 1.0)
        "alerts": [str]              # list of warning messages
    }
    """
    data = request.get_json()

    # ── Validate fields ───────────────────────────────────────────────────────
    required_fields = ['study_hours', 'self_study_hours', 'online_classes_hours', 'mental_health_score']
    missing = [f for f in required_fields if f not in data]
    if missing:
        return jsonify({'error': f'Missing fields: {missing}'}), 400

    try:
        study_hours          = float(data['study_hours'])
        self_study_hours     = float(data['self_study_hours'])
        online_classes_hours = float(data['online_classes_hours'])
        mental_health_score  = float(data['mental_health_score'])
    except (ValueError, TypeError) as e:
        return jsonify({'error': f'Invalid field value: {str(e)}'}), 400

    # ── Scale & predict ───────────────────────────────────────────────────────
    features       = np.array([[study_hours, self_study_hours, online_classes_hours, mental_health_score]])
    features_scaled = scaler.transform(features)

    exam_score_prob = model.predict_proba(features_scaled)[0][1]
    fail_prob       = 1 - exam_score_prob

    # ── Alerts ────────────────────────────────────────────────────────────────
    alerts = []
    if study_hours == 0:
        alerts.append("You haven't studied today. Try to study to increase your exam scores.")
    if mental_health_score < 5:
        alerts.append("Your mental health is not good. Relax or seek help to improve wellness.")
    if self_study_hours < 2:
        alerts.append("Self study hours are very low.")
    if online_classes_hours < 3:
        alerts.append("Online classes hours are short.")
    if exam_score_prob < 0.7:
        alerts.append(f"Your exam score probability is only {exam_score_prob * 100:.1f}%. Consider improving your study habits.")

    return jsonify({
        'exam_score_prob': round(float(exam_score_prob), 4),
        'fail_prob':       round(float(fail_prob), 4),
        'alerts':          alerts
    })


@app.route('/health', methods=['GET'])
def health():
    """Health check — confirms server and model are loaded."""
    return jsonify({'status': 'ok', 'model_loaded': model is not None, 'scaler_loaded': scaler is not None})


if __name__ == '__main__':
    print("=" * 52)
    print("  EduPredict API  —  http://0.0.0.0:5000")
    print("  POST /predict   →  get exam prediction")
    print("  GET  /health    →  server status")
    print("=" * 52)
    app.run(host='0.0.0.0', port=5000, debug=True)
